<?php

/**
 * Implements hook_menu()
 *
 * @return mixed
 */
function recuperacion_informacion_menu() {

  $items['buscador'] = array(
    'title' => t('Busqueda y recuperacion de informacion'),
    'description' => 'home page',
    'page callback' => '_search_process',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme()
 *
 * @return array
 */
function recuperacion_informacion_theme() {
  return array(
    'bartik' => array(
      'render element' => 'elements',
      'template' => 'templates/buscador',
    ),
  );
}

function _search_process() {

  $vars = array('process' => TRUE);

  if (isset($_POST['data']) && trim($_POST['data']['keys']) === "") {
    drupal_set_message(t('Por favor use algún parámetro de búsqueda'), 'error');
  }
  elseif (isset($_POST['data'])) {
    $data = $_POST['data'];

    $keys = $data['keys'];
    $cluster = isset($data['category']) ? 'true' : 'false';
    $results = $data['results'];

    $url = "http://190.121.139.11:8080/IRProject/rest/reuters/search/" .
      str_replace(' ', '+', $keys) . "/$cluster/$results";
    $options = array(
      'method' => 'GET',
    );

    $http_response = drupal_http_request($url, $options);
    $vars = json_decode($http_response->data, TRUE);
    $vars['keys'] = $data['keys'];
    $vars['show_cluster'] = isset($data['category']) ? true : false;
  }
  else {
    drupal_get_messages('error');
  }

  return theme('bartik', $vars);
}